services:
  farmos:
    image: farmos/farmos:3.2.0
    platform: linux/amd64
    ports:
      - "80:80"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=farmos
      - DB_USER=postgres
      - DB_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ./sites:/opt/drupal/web/sites
      - ./php.ini:/usr/local/etc/php/conf.d/farmos.ini
    depends_on:
      - postgres
    restart: unless-stopped

  postgres:
    image: postgres:15
    environment:
      - POSTGRES_DB=farmos
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_INITDB_ARGS=${POSTGRES_INITDB_ARGS:-}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5433:5432"
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@farmos.local
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD:-admin123}
      - PGADMIN_CONFIG_SERVER_MODE=False
    ports:
      - "8081:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  postgres_data:
  pgadmin_data:
